query getLatestRelease($owner: String!, $repo: String!) {
  repository(owner: $owner, name: $repo) {
    releases(first: 1) {
      nodes {
        tagName
      }
    }
  }
}

query getLatestInfo($owner: String!, $repo: String!) {
  repository(owner: $owner, name: $repo) {
    releases(first: 1) {
      nodes {
        url
        tagName
        description
        descriptionHTML
        updatedAt
      }
    }
  }
}

query getStableRelease($owner: String!, $repo: String!) {
  repository(owner: $owner, name: $repo) {
    latestRelease {
      tagName
    }
  }
}

query getStableInfo($owner: String!, $repo: String!) {
  repository(owner: $owner, name: $repo) {
    latestRelease {
      url
      tagName
      description
      descriptionHTML
      updatedAt
    }
  }
}
