properties:
  assertions:
  - resource: Microsoft.Windows.Developer/OsVersion
    directives:
      description: Verify min OS version requirement
      allowPrerelease: true
    settings:
      MinVersion: 10.0.18090
  resources:
  - directives:
      allowPrerelease: true
      acceptPackageAgreements: true
    settings:
      id: 7zip.7zip
      source: winget
    id: 7zip_7zip
    resource: Microsoft.WinGet.DSC/WinGetPackage
  - directives:
      allowPrerelease: true
      acceptPackageAgreements: true
    settings:
      id: AutoHotkey.AutoHotkey
      source: winget
    id: AutoHotkey_AutoHotkey
    resource: Microsoft.WinGet.DSC/WinGetPackage
  - directives:
      allowPrerelease: true
      acceptPackageAgreements: true
    settings:
      id: Git.Git
      source: winget
    id: Git_Git
    resource: Microsoft.WinGet.DSC/WinGetPackage
  - directives:
      allowPrerelease: true
      acceptPackageAgreements: true
    settings:
      id: RustDesk.RustDesk
      source: winget
    id: RustDesk_RustDesk
    resource: Microsoft.WinGet.DSC/WinGetPackage
  - directives:
      allowPrerelease: true
      acceptPackageAgreements: true
    settings:
      id: LocalSend.LocalSend
      source: winget
    id: LocalSend_LocalSend
    resource: Microsoft.WinGet.DSC/WinGetPackage
  - directives:
      allowPrerelease: true
      acceptPackageAgreements: true
    settings:
      id: Nutstore.Nutstore
      source: winget
    id: Nutstore_Nutstore
    resource: Microsoft.WinGet.DSC/WinGetPackage
  - directives:
      allowPrerelease: true
      acceptPackageAgreements: true
    settings:
      id: voidtools.Everything
      source: winget
    id: voidtools_Everything
    resource: Microsoft.WinGet.DSC/WinGetPackage
  - directives:
      allowPrerelease: true
      acceptPackageAgreements: true
    settings:
      id: Nvidia.GeForceExperience
      source: winget
    id: Nvidia_GeForceExperience
    resource: Microsoft.WinGet.DSC/WinGetPackage
  - directives:
      allowPrerelease: true
      acceptPackageAgreements: true
    settings:
      id: Microsoft.PowerShell
      source: winget
    id: Microsoft_PowerShell
    resource: Microsoft.WinGet.DSC/WinGetPackage
  - directives:
      allowPrerelease: true
      acceptPackageAgreements: true
    settings:
      id: Microsoft.Edge
      source: winget
    id: Microsoft_Edge
    resource: Microsoft.WinGet.DSC/WinGetPackage
  - directives:
      allowPrerelease: true
      acceptPackageAgreements: true
    settings:
      id: Microsoft.EdgeWebView2Runtime
      source: winget
    id: Microsoft_EdgeWebView2Runtime
    resource: Microsoft.WinGet.DSC/WinGetPackage
  - directives:
      allowPrerelease: true
      acceptPackageAgreements: true
    settings:
      id: Tencent.WeChat
      source: winget
    id: Tencent_WeChat
    resource: Microsoft.WinGet.DSC/WinGetPackage
  - directives:
      allowPrerelease: true
      acceptPackageAgreements: true
    settings:
      id: Intel.IntelDriverAndSupportAssistant
      source: winget
    id: Intel_IntelDriverAndSupportAssistant
    resource: Microsoft.WinGet.DSC/WinGetPackage
  - directives:
      allowPrerelease: true
      acceptPackageAgreements: true
    settings:
      id: Baidu.BaiduNetdisk
      source: winget
    id: Baidu_BaiduNetdisk
    resource: Microsoft.WinGet.DSC/WinGetPackage
  - directives:
      allowPrerelease: true
      acceptPackageAgreements: true
    settings:
      id: BurntSushi.ripgrep.MSVC
      source: winget
    id: BurntSushi_ripgrep_MSVC
    resource: Microsoft.WinGet.DSC/WinGetPackage
  - directives:
      allowPrerelease: true
      acceptPackageAgreements: true
    settings:
      id: Kingsoft.WPSOffice.CN
      source: winget
    id: Kingsoft_WPSOffice_CN
    resource: Microsoft.WinGet.DSC/WinGetPackage
  - directives:
      allowPrerelease: true
      acceptPackageAgreements: true
    settings:
      id: aria2.aria2
      source: winget
    id: aria2_aria2
    resource: Microsoft.WinGet.DSC/WinGetPackage
  - directives:
      allowPrerelease: true
      acceptPackageAgreements: true
    settings:
      id: bootandy.dust
      source: winget
    id: bootandy_dust
    resource: Microsoft.WinGet.DSC/WinGetPackage
  - directives:
      allowPrerelease: true
      acceptPackageAgreements: true
    settings:
      id: junegunn.fzf
      source: winget
    id: junegunn_fzf
    resource: Microsoft.WinGet.DSC/WinGetPackage
  - directives:
      allowPrerelease: true
      acceptPackageAgreements: true
    settings:
      id: sharkdp.bat
      source: winget
    id: sharkdp_bat
    resource: Microsoft.WinGet.DSC/WinGetPackage
  - directives:
      allowPrerelease: true
      acceptPackageAgreements: true
    settings:
      id: sharkdp.fd
      source: winget
    id: sharkdp_fd
    resource: Microsoft.WinGet.DSC/WinGetPackage
  - directives:
      allowPrerelease: true
      acceptPackageAgreements: true
    settings:
      id: Python.Python.3.12
      source: winget
    id: Python_Python_3_12
    resource: Microsoft.WinGet.DSC/WinGetPackage
  - directives:
      allowPrerelease: true
      acceptPackageAgreements: true
    settings:
      id: Microsoft.PowerToys
      source: winget
    id: Microsoft_PowerToys
    resource: Microsoft.WinGet.DSC/WinGetPackage
  - directives:
      allowPrerelease: true
      acceptPackageAgreements: true
    settings:
      id: Microsoft.VisualStudioCode
      source: winget
    id: Microsoft_VisualStudioCode
    resource: Microsoft.WinGet.DSC/WinGetPackage
  - directives:
      allowPrerelease: true
      acceptPackageAgreements: true
    settings:
      id: ImageMagick.Q16-HDRI
      source: winget
    id: ImageMagick_Q16_HDRI
    resource: Microsoft.WinGet.DSC/WinGetPackage
  - directives:
      allowPrerelease: true
      acceptPackageAgreements: true
    settings:
      id: Microsoft.WindowsTerminal
      source: winget
    id: Microsoft_WindowsTerminal
    resource: Microsoft.WinGet.DSC/WinGetPackage
  - resource: PackageManagement/PackageManagementSource
    settings:
      Name: PSGallery
      SourceLocation: https://www.powershellgallery.com/api/v2/
      InstallationPolicy: Trusted
      ProviderName: PowerShellGet
  - settings:
      ProviderName: PowerShellGet
      Name: PSDesiredStateConfiguration
      Ensure: Present
      Source: PSGallery
    id: PSDesiredStateConfiguration
    resource: PackageManagement/PackageManagement
  - settings:
      ProviderName: PowerShellGet
      Name: PSDscResources
      Ensure: Present
      Source: PSGallery
    id: PSDscResources
    resource: PackageManagement/PackageManagement
  - settings:
      ProviderName: PowerShellGet
      Name: ComputerManagementDsc
      Ensure: Present
      Source: PSGallery
    id: ComputerManagementDsc
    resource: PackageManagement/PackageManagement
  - settings:
      ProviderName: PowerShellGet
      Name: Microsoft.WinGet.CommandNotFound
      Ensure: Present
      Source: PSGallery
    id: Microsoft_WinGet_CommandNotFound
    resource: PackageManagement/PackageManagement
  - settings:
      ProviderName: PowerShellGet
      Name: Microsoft.WinGet.Client
      Ensure: Present
      Source: PSGallery
    id: Microsoft_WinGet_Client
    resource: PackageManagement/PackageManagement
  - settings:
      ProviderName: PowerShellGet
      Name: Microsoft.WinGet.DSC
      Ensure: Present
      Source: PSGallery
    id: Microsoft_WinGet_DSC
    resource: PackageManagement/PackageManagement
  - settings:
      ProviderName: PowerShellGet
      Name: Microsoft.Windows.Developer
      Ensure: Present
      Source: PSGallery
    id: Microsoft_Windows_Developer
    resource: PackageManagement/PackageManagement
  - settings:
      ProviderName: PowerShellGet
      Name: Refresh-EnvironmentVariables
      Ensure: Present
      Source: PSGallery
    id: Refresh_EnvironmentVariables
    resource: PackageManagement/PackageManagement
  - settings:
      ProviderName: PowerShellGet
      Name: powershell-yaml
      Ensure: Present
      Source: PSGallery
    id: powershell_yaml
    resource: PackageManagement/PackageManagement
  - resource: Microsoft.Windows.Developer/DeveloperMode
    directives:
      description: Enable Developer Mode
      allowPrerelease: true
    settings:
      Ensure: Present
  - resource: Microsoft.Windows.Developer/Taskbar
    settings:
      SearchboxMode: Hide
      WidgetsButton: Hide
      TaskViewButton: Hide
      HideLabelsMode: Always
  - resource: Microsoft.WinGet.DSC/WinGetAdminSettings
    settings:
      Settings: >-
        {
          "$schema": "https://raw.githubusercontents.com/microsoft/winget-cli/master/schemas/JSON/settings/settings.schema.0.2.json",
          "installBehavior": {
            "preferences": {
              "scope": "machine"
            }
          },
          "uninstallBehavior": {
            "purgePortablePackage": true
          },
          "telemetry": {
            "disable": true
          },
          "experimentalFeatures": {
            "resume": true,
            "configureExport": true,
            "configureSelfElevate": true,
            "directMSI": true,
            "experimentalARG": true,
            "experimentalCMD": true
          }
        }
  - resource: Microsoft.Windows.Developer/EnableDarkMode
    settings:
      Ensure: Present
  - resource: ComputerManagementDsc/WindowsOptionalFeature
    settings:
      Name: NetFx3
      Ensure: Present
  - resource: Microsoft.PowerToys.Configure/PowerRename
    settings:
      Enabled: false
  - resource: Microsoft.PowerToys.Configure/AlwaysOnTop
    settings:
      Enabled: true
      FrameThickness: 2
      DoNotActivateOnGameMode: true
  - resource: Microsoft.PowerToys.Configure/Awake
    settings:
      Enabled: false
  - resource: Microsoft.PowerToys.Configure/ColorPicker
    settings:
      Enabled: true
      CopiedColorRepresentation: HEX
      ActivationAction: OpenColorPickerAndThenEditor
      ShowColorName: true
  - resource: Microsoft.PowerToys.Configure/CropAndLock
    settings:
      Enabled: false
  - resource: Microsoft.PowerToys.Configure/EnvironmentVariables
    settings:
      Enabled: true
      LaunchAdministrator: true
  - resource: Microsoft.PowerToys.Configure/FancyZones
    settings:
      Enabled: false
  - resource: Microsoft.PowerToys.Configure/FileLocksmith
    settings:
      Enabled: false
  - resource: Microsoft.PowerToys.Configure/FindMyMouse
    settings:
      Enabled: false
  - resource: Microsoft.PowerToys.Configure/Hosts
    settings:
      Enabled: false
  - resource: Microsoft.PowerToys.Configure/ImageResizer
    settings:
      Enabled: false
  - resource: Microsoft.PowerToys.Configure/Peek
    settings:
      Enabled: false
  - resource: Microsoft.PowerToys.Configure/KeyboardManager
    settings:
      Enabled: false
  - resource: Microsoft.PowerToys.Configure/ShortcutGuide
    settings:
      Enabled: false
  - resource: Microsoft.PowerToys.Configure/VideoConference
    settings:
      Enabled: false
  - resource: Microsoft.PowerToys.Configure/GeneralSettings
    settings:
      Startup: true
      EnableWarningsElevatedApps: true
      Theme: System
      ShowNewUpdatesToastNotification: false
      AutoDownloadUpdates: false
      ShowWhatsNewAfterUpdates: true
      EnableExperimentation: false
  - resource: Microsoft.PowerToys.Configure/MeasureTool
    settings:
      Enabled: false
  - resource: Microsoft.PowerToys.Configure/MouseHighlighter
    settings:
      Enabled: true
      DefaultMeasureStyle: 1
  - resource: Microsoft.PowerToys.Configure/MouseJump
    settings:
      Enabled: false
  - resource: Microsoft.PowerToys.Configure/MousePointerCrosshairs
    settings:
      Enabled: false
      CrosshairsThickness: 2
      CrosshairsBorderSize: 0
      CrosshairsAutoHide: true
      CrosshairsRadius: 0
  - resource: Microsoft.PowerToys.Configure/MouseWithoutBorders
    settings:
      Enabled: false
  - resource: Microsoft.PowerToys.Configure/PastePlain
    settings:
      Enabled: false
  - resource: Microsoft.PowerToys.Configure/PowerPreview
    settings:
      Enabled: false
  - resource: Microsoft.PowerToys.Configure/RegistryPreview
    settings:
      Enabled: false
  - resource: Microsoft.PowerToys.Configure/PowerAccent
    settings:
      Enabled: false
  - resource: Microsoft.PowerToys.Configure/PowerLauncher
    settings:
      Enabled: true
  - resource: Microsoft.PowerToys.Configure/PowerOcr
    settings:
      Enabled: true
  - settings:
      Ensure: Present
      Name: LESS
      Value: --quit-if-one-screen --use-color --wordwrap --mouse --ignore-case --incsearch --search-options=W -R
    id: LESS
    resource: PSDscResources/Environment
  - settings:
      Ensure: Present
      Name: EDITOR
      Value: nvim
    id: EDITOR
    resource: PSDscResources/Environment
  - settings:
      Ensure: Present
      Name: PAGER
      Value: less
    id: PAGER
    resource: PSDscResources/Environment
  configurationVersion: 0.2.0
