$schema: https://aka.ms/dsc/schemas/v3/bundled/config/document.vscode.json
parameters:
  date:
    type: int
    description: current date
    defaultValue: "[utcNow()]"
resources:
  - type: Microsoft.DSC.Debug/Echo
    name: echo date
    properties:
      output: "[parameters('date')]"
