properties:
  configurationVersion: 0.2.0
  assertions:
    - resource: Microsoft.Windows.Developer/OsVersion
      settings:
        MinVersion: 10.0.22000
      directives:
        description: Verify min OS version requirement
        allowPrerelease: true
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      settings:
        id: Microsoft.PowerToys
        source: winget
      directives:
        description: Microsoft_PowerToys
        allowPrerelease: true
      id: Microsoft_PowerToys
  resources:
    - resource: PSDscResources/Environment
      settings:
        Value: --quit-if-one-screen --use-color --wordwrap --mouse --ignore-case --incsearch --search-options=W -R
        Name: LESS
        Ensure: Present
      directives:
        description: LESS
      id: LESS
    - resource: PSDscResources/Environment
      settings:
        Value: nvim
        Name: EDITOR
        Ensure: Present
      directives:
        description: EDITOR
      id: EDITOR
    - resource: PSDscResources/Environment
      settings:
        Value: less
        Name: PAGER
        Ensure: Present
      directives:
        description: PAGER
      id: PAGER
    - resource: PSDscResources/Environment
      settings:
        Value: https://goproxy.cn,direct
        Name: GOPROXY
        Ensure: Present
      directives:
        description: GOPROXY
      id: GOPROXY
    - resource: Microsoft.Windows.Developer/DeveloperMode
      settings:
        Ensure: Present
      directives:
        description: Microsoft.Windows.Developer/DeveloperMode
        allowPrerelease: true
    - resource: Microsoft.Windows.Developer/Taskbar
      settings:
        Alignment: Middle
        SearchboxMode: SearchBox
        WidgetsButton: Hide
        TaskViewButton: Show
        HideLabelsMode: Always
      directives:
        description: Microsoft.Windows.Developer/Taskbar
        allowPrerelease: true
    - resource: Microsoft.Windows.Developer/WindowsExplorer
      settings:
        FileExtensions: Show
        HiddenFiles: Show
        ItemCheckBoxes: Hide
      directives:
        description: Microsoft.Windows.Developer/WindowsExplorer
        allowPrerelease: true
    - resource: Microsoft.Windows.Developer/EnableDarkMode
      settings:
        Ensure: Present
      directives:
        description: Microsoft.Windows.Developer/EnableDarkMode
        allowPrerelease: true
    - resource: Microsoft.WinGet.DSC/WinGetAdminSettings
      settings:
        Settings:
          $schema: https://raw.githubusercontents.com/microsoft/winget-cli/master/schemas/JSON/settings/settings.schema.0.2.json
          installBehavior:
            preferences:
              scope: machine
          uninstallBehavior:
            purgePortablePackage: true
          telemetry:
            disable: true
          experimentalFeatures:
            resume: true
            configureExport: true
            configureSelfElevate: true
            directMSI: true
            experimentalARG: true
            experimentalCMD: true
      directives:
        description: Microsoft.WinGet.DSC/WinGetAdminSettings
        allowPrerelease: true
    - directives:
        description: Configure PowerToys
      settings:
        AlwaysOnTop:
          Enabled: true
          DoNotActivateOnGameMode: true
          FrameThickness: 2
        Awake:
          Enabled: false
        ColorPicker:
          Enabled: true
          ShowColorName: true
          CopiedColorRepresentation: HEX
          ActivationAction: OpenColorPickerAndThenEditor
        CropAndLock:
          Enabled: false
        EnvironmentVariables:
          Enabled: true
          LaunchAdministrator: true
        FancyZones:
          Enabled: false
        FileLocksmith:
          Enabled: false
        FindMyMouse:
          Enabled: false
        GeneralSettings:
          Startup: true
          ShowNewUpdatesToastNotification: false
          EnableExperimentation: false
          AutoDownloadUpdates: false
          Theme: System
          EnableWarningsElevatedApps: true
          ShowWhatsNewAfterUpdates: true
        Hosts:
          Enabled: true
        ImageResizer:
          Enabled: false
        KeyboardManager:
          Enabled: false
        MeasureTool:
          Enabled: true
        MouseHighlighter:
          Enabled: false
        MouseJump:
          Enabled: false
        MousePointerCrosshairs:
          Enabled: false
          CrosshairsThickness: 2
          CrosshairsBorderSize: 0
          CrosshairsAutoHide: true
          CrosshairsRadius: 0
        MouseWithoutBorders:
          Enabled: false
        # absent key
        # PastePlain:
        #   Enabled: false
        Peek:
          Enabled: false
        PowerAccent:
          Enabled: false
        PowerLauncher:
          Enabled: true
        PowerOcr:
          Enabled: true
        PowerPreview:
          Enabled: false
        PowerRename:
          Enabled: false
        RegistryPreview:
          Enabled: true
        ShortcutGuide:
          Enabled: false
        VideoConference:
          Enabled: false
      resource: Microsoft.PowerToys.Configure/PowerToysConfigure
