properties:
  configurationVersion: 0.2.0
  assertions:
    - resource: Microsoft.Windows.Developer/OsVersion
      settings:
        MinVersion: 10.0.18090
      directives:
        description: Verify min OS version requirement
        allowPrerelease: true
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      settings:
        id: Microsoft.PowerToys
        source: winget
      directives:
        description: Microsoft_PowerToys
        allowPrerelease: true
      id: Microsoft_PowerToys
  resources:
    - resource: PackageManagement/PackageManagementSource
      settings:
        ProviderName: PowerShellGet
        SourceLocation: https://www.powershellgallery.com/api/v2/
        Name: PSGallery
        InstallationPolicy: Trusted
      directives:
        description: PackageManagement/PackageManagementSource
        allowPrerelease: true
    - resource: PackageManagement/PackageManagement
      settings:
        Source: PSGallery
        Ensure: Present
        Name: PSDesiredStateConfiguration
        ProviderName: PowerShellGet
      directives:
        description: PSDesiredStateConfiguration
        allowPrerelease: true
      id: PSDesiredStateConfiguration
    - resource: PackageManagement/PackageManagement
      settings:
        Source: PSGallery
        Ensure: Present
        Name: PSDscResources
        ProviderName: PowerShellGet
      directives:
        description: PSDscResources
        allowPrerelease: true
      id: PSDscResources
    - resource: PackageManagement/PackageManagement
      settings:
        Source: PSGallery
        Ensure: Present
        Name: ComputerManagementDsc
        ProviderName: PowerShellGet
      directives:
        description: ComputerManagementDsc
        allowPrerelease: true
      id: ComputerManagementDsc
    - resource: PackageManagement/PackageManagement
      settings:
        Source: PSGallery
        Ensure: Present
        Name: Microsoft.WinGet.CommandNotFound
        ProviderName: PowerShellGet
      directives:
        description: Microsoft_WinGet_CommandNotFound
        allowPrerelease: true
      id: Microsoft_WinGet_CommandNotFound
    - resource: PackageManagement/PackageManagement
      settings:
        Source: PSGallery
        Ensure: Present
        Name: Microsoft.WinGet.Client
        ProviderName: PowerShellGet
      directives:
        description: Microsoft_WinGet_Client
        allowPrerelease: true
      id: Microsoft_WinGet_Client
    - resource: PackageManagement/PackageManagement
      settings:
        Source: PSGallery
        Ensure: Present
        Name: Microsoft.WinGet.DSC
        ProviderName: PowerShellGet
      directives:
        description: Microsoft_WinGet_DSC
        allowPrerelease: true
      id: Microsoft_WinGet_DSC
    - resource: PackageManagement/PackageManagement
      settings:
        Source: PSGallery
        Ensure: Present
        Name: Microsoft.Windows.Developer
        ProviderName: PowerShellGet
      directives:
        description: Microsoft_Windows_Developer
        allowPrerelease: true
      id: Microsoft_Windows_Developer
    - resource: PackageManagement/PackageManagement
      settings:
        Source: PSGallery
        Ensure: Present
        Name: Refresh-EnvironmentVariables
        ProviderName: PowerShellGet
      directives:
        description: Refresh_EnvironmentVariables
        allowPrerelease: true
      id: Refresh_EnvironmentVariables
    - resource: PackageManagement/PackageManagement
      settings:
        Source: PSGallery
        Ensure: Present
        Name: powershell-yaml
        ProviderName: PowerShellGet
      directives:
        description: powershell_yaml
        allowPrerelease: true
      id: powershell_yaml
    - resource: Microsoft.Windows.Developer/DeveloperMode
      settings:
        Ensure: Present
      directives:
        description: Microsoft.Windows.Developer/DeveloperMode
        allowPrerelease: true
    - resource: Microsoft.Windows.Developer/Taskbar
      settings:
        SearchboxMode: Hide
        WidgetsButton: Hide
        TaskViewButton: Hide
        HideLabelsMode: Always
      directives:
        description: Microsoft.Windows.Developer/Taskbar
        allowPrerelease: true
    - resource: Microsoft.WinGet.DSC/WinGetAdminSettings
      settings:
        Settings:
          $schema: https://raw.githubusercontents.com/microsoft/winget-cli/master/schemas/JSON/settings/settings.schema.0.2.json
          installBehavior:
            preferences:
              scope: machine
          uninstallBehavior:
            purgePortablePackage: true
          telemetry:
            disable: true
          experimentalFeatures:
            resume: true
            configureExport: true
            configureSelfElevate: true
            directMSI: true
            experimentalARG: true
            experimentalCMD: true
      directives:
        description: Microsoft.WinGet.DSC/WinGetAdminSettings
        allowPrerelease: true
    - resource: Microsoft.Windows.Developer/EnableDarkMode
      settings:
        Ensure: Present
      directives:
        description: Microsoft.Windows.Developer/EnableDarkMode
        allowPrerelease: true
    - resource: ComputerManagementDsc/WindowsOptionalFeature
      settings:
        Ensure: Present
        Name: NetFx3
      directives:
        description: ComputerManagementDsc/WindowsOptionalFeature
        allowPrerelease: true
    - directives:
        description: Configure PowerToys
      settings:
        AlwaysOnTop:
          Enabled: true
          DoNotActivateOnGameMode: true
          FrameThickness: 2
        Awake:
          Enabled: true
        ColorPicker:
          Enabled: true
          ShowColorName: true
          CopiedColorRepresentation: HEX
          ActivationAction: OpenColorPickerAndThenEditor
        CropAndLock:
          Enabled: false
        EnvironmentVariables:
          Enabled: false
          LaunchAdministrator: true
        FancyZones:
          Enabled: false
        FileLocksmith:
          Enabled: false
        FindMyMouse:
          Enabled: false
        GeneralSettings:
          Startup: true
          ShowNewUpdatesToastNotification: false
          EnableExperimentation: false
          AutoDownloadUpdates: false
          Theme: System
          EnableWarningsElevatedApps: true
          ShowWhatsNewAfterUpdates: true
        Hosts:
          Enabled: false
        ImageResizer:
          Enabled: false
        KeyboardManager:
          Enabled: false
        MeasureTool:
          Enabled: true
        MouseHighlighter:
          Enabled: false
        MouseJump:
          Enabled: false
        MousePointerCrosshairs:
          Enabled: false
          CrosshairsThickness: 2
          CrosshairsBorderSize: 0
          CrosshairsAutoHide: true
          CrosshairsRadius: 0
        MouseWithoutBorders:
          Enabled: false
        Peek:
          Enabled: false
        PowerAccent:
          Enabled: false
        PowerLauncher:
          Enabled: false
        PowerOcr:
          Enabled: false
        PowerPreview:
          Enabled: false
        PowerRename:
          Enabled: false
        RegistryPreview:
          Enabled: true
        ShortcutGuide:
          Enabled: false
        VideoConference:
          Enabled: false
      resource: Microsoft.PowerToys.Configure/PowerToysConfigure
    - resource: PSDscResources/Environment
      settings:
        Value: --quit-if-one-screen --use-color --wordwrap --mouse --ignore-case --incsearch --search-options=W -R
        Name: LESS
        Ensure: Present
      directives:
        description: LESS
        allowPrerelease: true
      id: LESS
    - resource: PSDscResources/Environment
      settings:
        Value: nvim
        Name: EDITOR
        Ensure: Present
      directives:
        description: EDITOR
        allowPrerelease: true
      id: EDITOR
    - resource: PSDscResources/Environment
      settings:
        Value: less
        Name: PAGER
        Ensure: Present
      directives:
        description: PAGER
        allowPrerelease: true
      id: PAGER
